---

# Set up a cron job to reboot the pi

- name: Add crontab entry to reboot the machine between 0100 and 0200 every night
  cron:
    name: 'Reboot between 0100 and 0200 every night, otherwise the Pi locks up after a few days'
    job: '/sbin/reboot | logger -i -t "nightly reboot"'
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: '1'
    state: present
  become: yes
