---

# Set up a Twitter API wrapper and various calls to it

- name: Pip install Github Pages Archiver
  pip:
    name: git+git://github.com/agude/github-pages-archiver
    state: forcereinstall
    editable: false
    executable: "{{ ansible_env.HOME }}/bin/miniconda/bin/pip"

- name: Adding pages to github archiver
  cron:
    name: 'Backup {{ item.site }} on Archive.org'
    special_time: daily
    job: "{{ ansible_env.HOME }}/bin/miniconda/bin/archiver {{ item.sitemap }} 2>&1 | logger -i -t 'Archiver' && {{ ansible_env.HOME }}/bin/miniconda/bin/t -s '{{ item.site }} backed up!' 2>&1 | logger -i -t 'Twitter Bot: Archiver'"
    state: present
  with_items:
    - { sitemap: 'https://alexgude.com/sitemap.xml', site: 'https://alexgude.com' }
    - { sitemap: 'http://charles.uno/sitemap.xml', site: 'http://charles.uno' }
    - { sitemap: 'https://www.radiokeysmusic.com/sitemap.xml', site: 'https://www.radiokeysmusic.com' }
