---

# Set up a Twitter API wrapper and various calls to it

- name: Install Pip
  apt:
    name: python-pip
    state: latest
  become: true

- name: Pip install Raspberry Pi Twitter Bot
  pip:
    name: git+git://github.com/agude/raspberry-pi-twitter-bot.git
    state: forcereinstall
    editable: false

- name: Set fact with twitter script and Caltrain script locations
  set_fact:
    twitter_bot_script_location: "{{ ansible_env.HOME }}/.local/bin/t"

- name: Check that the Twitter Bot exists
  include: check-executable-location.yaml
  with_items:
    - "{{ twitter_bot_script_location }}"

- name: Creating configuration directory
  file:
    path: "{{ ansible_env.HOME }}/.config/rpi-twitter"
    state: directory
    mode: "u=rwx,go="

- name: Copying twitter keys and config
  copy:
    src: "roles/raspberry_pi/vault/config_{{ inventory_hostname }}.json"
    dest: "{{ ansible_env.HOME }}/.config/rpi-twitter/config"
    mode: "u=rw,go="

- name: Add crontab entry to tweet when the machine powers on
  cron:
    name: 'Tweet after rebooting'
    job: "sleep 10 && {{ twitter_bot_script_location }} -s 'Good morning! I just came back up from reboot!' 2>&1 | logger -i -t 'Twitter Bot: Reboot'"
    special_time: reboot
    state: present

- name: Add crontab entry to add Twitter heartbeat
  cron:
    name: 'Tweet daily heartbeat'
    job: '{{ twitter_bot_script_location }} -s "I am still alive!" | logger -i -t "twitter heartbeat'
    special_time: daily
    state: present
  become: yes
