---

# Set up a Ubiquiti Unifi controller

- name: Import MongoDB key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 0C49F3730359A14518585931BC711F9BA15703C6
  become: true

- name: Add MongoDB repository
  apt_repository:
    filename: '/etc/apt/sources.list.d/mongodb-org-3.4.list'
    repo: 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse'
    state: present
    update_cache: true
  become: true

- name: Add Unifi signing key
  apt_key:
    url: https://dl.ubnt.com/unifi/unifi-repo.gpg
    state: present
  become: true

#- name: Add Unifi PPA
#  apt_repository:
#    filename: '/etc/apt/sources.list.d/unifi.list'
#    repo: deb http://www.ui.com/downloads/unifi/debian stable ubiquiti
#    state: present
#    update_cache: true
#  become: true
#  when: ansible_architecture != 'aarch64'
#
#- name: Installing Unifi controller
#  apt:
#    name: "unifi"
#    state: latest
#  become: true
#  when: ansible_architecture != 'aarch64'

- name: Installing Unifi controller
  apt:
    deb: https://dl.ubnt.com/unifi/5.10.25/unifi_sysvinit_all.deb
  become: true
  when: ansible_architecture == 'aarch64'

# Fails when MongoDB isn't running
#- name: Disabling non-Unifi MongoDB
#  systemd:
#    name: mongodb
#    enabled: no
#  become: true

- name: Add user to unifi so they can copy backup files
  user:
    name: "{{ lookup('env','USER') }}"
    groups: unifi
    append: true
  become: true

# Might need to dpkg the package, then apt-get -f install
