---

- name: Set fact with twitter script and Caltrain script locations
  set_fact:
    caltain_bot_script_location: "{{ ansible_env.HOME }}/.local/bin/caltrain-checker"

- name: Check that the Caltrain Bot exists
  include: check-executable-location.yaml
  with_items:
    - "{{ caltain_bot_script_location }}"

- name: Adding caltrain twitter module to crontab
  cron:
    name: 'Check Caltrain Status for {{ item.period }} commute'
    hour: '{{ item.hour }}'
    minute: '{{ item.minute }}'
    weekday: 1-5
    job: "{{ caltain_bot_script_location }} -t {{ item.trains }} nb -m caltrain -b {{ item.start }} -e {{ item.end }} -s -r alex_gude | logger -i -t 'Twitter Bot: Caltrain'"
    state: present
  with_items:
    - { period: 'morning', trains: '227 nb', start: '6', end: '9', hour: '8', minute: '0,15,30' }
    - { period: 'evening', trains: '264 268 sb', start: '15', end: '18', hour: '16,17', minute: '0,15,30,45' }
