---

- include: setup-ntp.yaml
- include: fix-xconsole-syslog.yaml
- include: crontab-reboot.yaml
- include: crontab-kernel-update.yaml
- include: uninstall-unused.yaml
- include: install-miniconda.yaml
- include: install-twitter-bot.yaml
- include: setup-deluge.yaml
  when: torrent_server == true
- include: blacklist-wifi.yaml
  when: raspberry_pi_version == 3
- include: install-github-pages-archiver.yaml
  when: archiver == true
- include: install-unifi-controller.yaml
  when: unifi == true
