---

  - include: setup-ntp.yaml
  - include: crontab-reboot.yaml
  - include: uninstall-unused.yaml
  - include: blacklist-wifi.yaml
    when: raspberry_pi_version == 3
  - include: install-miniconda.yaml
