---

# Set up a Twitter API wrapper and various calls to it

- name: Install SQLite3
  apt:
    name: sqlite3
    state: latest
  become: true

- name: Make SQLite data directory
  file:
    path: "{{ ansible_env.HOME }}/data/"
    state: directory
    mode: "u=rwX,go="

- name: Create temperature database
  shell: |
    sqlite3 "data.sqlite3" << EOF
    CREATE TABLE IF NOT EXISTS temperature (
      datetime_id INTEGER PRIMARY KEY,
      temperature INTEGER NOT NULL
    );
    EOF
  args:
    chdir: "{{ ansible_env.HOME }}/data/"

- name: Copy temperature logging script
  copy:
    src: "roles/raspberry_pi/files/write_temperature_to_sqlite.sh"
    dest: "{{ ansible_env.HOME }}/data/"
    mode: "u=rx,go="

- name: Add crontab entry to log the temperature
  cron:
    name: 'Temperature logger'
    job: '{{ ansible_env.HOME }}/data/write_temperature_to_sqlite.sh'
    state: present
