---

# Remove unneeded default packages

- name: Remove unused default packages on all Raspberry Pis
  apt:
    name: 
      - atril*
      - avahi*
      - brasero*
      - brltty
      - cheese*
      - cups-*
      - deja-dup*
      - hexchat*
      - idle*
      - libreoffice*
      - minecraft-pi
      - pidgin*
      - plank
      - pluma*
      - qjackctl
      - rhythmbox*
      - scratch
      - shotwell*
      - simple-scan
      - sonic-pi*
      - synapse
      - thunderbird*
      - transmission*
      - ubuntu-mate-welcome*
      - vlc*
      - youtube-dl*
    state: absent
    purge: yes
    autoremove: yes
  become: yes

- name: Remove unused default packages on Raspberry Pi 3s
  apt:
    name:
      - python-picraft*
    state: absent
    purge: yes
    autoremove: yes
  become: yes
  when: raspberry_pi_version == 3
