---
- name: All Linux machines
  hosts: all
  roles:
    - common
    - livepatch

- name: Desktop machines
  hosts: desktops
  roles:
    - desktop

- name: Raspberry Pi base setup
  hosts: pis
  roles:
    - pi
