---
galaxy_info:
  role_name: goose
  namespace: agude
  author: agude
  description: Install Goose desktop app
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - oracular

dependencies: []
