---

# Install anaconda

- name: Download the anaconda package
  get_url:
    url: https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh
    dest: /tmp/Anaconda3.sh
    mode: "u+rwx"

- name: Install anaconda
  command: "./Anaconda3.sh -b -p {{ ansible_env.HOME }}/bin/anaconda"
  args:
    chdir: /tmp
    creates: "{{ ansible_env.HOME }}/bin/anaconda"
