---

# Install packages

- include_vars: vars/apt-packages.yaml

- name: Apt install various programs
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true
  with_items: "{{ packages.pc }}"
