---

# Install packages

- name: Apt install various programs
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true
  with_items:
    - audacity
    - backintime-gnome
    - banshee
    - build-essential
    - compizconfig-settings-manager
    - conky
    - dconf-tools
    - deluge
    - exuberant-ctags
    - getmail4
    - gimp
    - git
    - gnome-do
    - gparted
    - gpm
    - graphicsmagick-imagemagick-compat
    - homebank
    - inkscape
    - latexmk
    - libxml2-utils
    - lyx
    - meld
    - openssh-blacklist
    - openssh-blacklist-extra
    - openssh-server
    - pandoc
    - pdftk
    - pep8
    - pidgin
    - pidgin-otr
    - preload
    - python3
    - python3-numpy
    - python3-scipy
    - screen
    - ubuntu-restricted-*
    - viking
    - vim-gnome
    - xclip
