---

# Remove unneeded default packages

- include_vars: vars/apt-packages.yaml

- name: Remove unused default packages
  apt:
    name: "{{ remove.pc.all }}"
    state: absent
    purge: true
  become: true

- name: Remove 16.04 specific unused default packages
  apt:
    name: "{{ remove.pc.xenial }}"
    state: absent
    purge: true
  become: true
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "16.04"
