---
- name: Ensure github.com is a known host
  ansible.builtin.known_hosts:
    name: github.com
    key: "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl"
    state: present

- name: Clone dotfiles
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ user }}/.dotfiles"
    version: main
    ssh_opts: "-o ForwardAgent=yes"
  become: true
  become_user: "{{ user }}"

- name: Run dotfiles install
  ansible.builtin.command:
    cmd: script -qe -c "./install.sh --profile {{ dotfiles_profile }}" /dev/null
    chdir: "/home/{{ user }}/.dotfiles"
  become: true
  become_user: "{{ user }}"
  changed_when: false

- name: Clone Knowledge repo
  ansible.builtin.git:
    repo: "{{ knowledge_repo }}"
    dest: "/home/{{ user }}/Knowledge"
    version: main
    ssh_opts: "-o ForwardAgent=yes"
  become: true
  become_user: "{{ user }}"

- name: Run Knowledge install
  ansible.builtin.command:
    cmd: scripts/install
    chdir: "/home/{{ user }}/Knowledge"
  become: true
  become_user: "{{ user }}"
  changed_when: false
  when: not ansible_check_mode

- name: Clone Wiki repo
  ansible.builtin.git:
    repo: "{{ wiki_repo }}"
    dest: "/home/{{ user }}/Wiki"
    version: main
    ssh_opts: "-o ForwardAgent=yes"
  become: true
  become_user: "{{ user }}"

- name: Run Wiki install
  ansible.builtin.command:
    cmd: scripts/install
    chdir: "/home/{{ user }}/Wiki"
  become: true
  become_user: "{{ user }}"
  changed_when: false
  when: not ansible_check_mode
