---

# Install my dotfiles from Github

- name: Update apt cache and install the "git" and "vim" packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  become: true
  with_items:
    - git
    - vim-gnome

- name: Ensure github.com is a known host
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
    regexp: "^github\\.com"

- name: Clone dotfiles git repo
  git:
    repo: ssh://git@github.com/agude/dotfiles.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    update: yes

- name: Run the dotfiles installer in ".dotfiles"
  shell: "{{ ansible_env.HOME }}/.dotfiles/install.sh"
  args:
    chdir: "{{ ansible_env.HOME }}/.dotfiles/"
    executable: /bin/bash
