---

# Install Various programs

- include_vars: vars/apt-packages.yaml

- name: Apt install various programs
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true
  with_items: "{{ packages.common }}"

- name: Apt install 16.04 specific programs
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true
  with_items: "{{ packages.common_xenial }}"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "16.04"
