---

# Install Various programs

- include_vars: vars/apt-packages.yaml

- name: Apt install various programs
  apt:
    name: "{{ install.common.all }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Apt install 16.04 specific programs
  apt:
    name: "{{ install.common.xenial }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "16.04"

- name: Apt install 18.04 specific programs
  apt:
    name: "{{ install.common.bionic }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "18.04"
      
- name: Apt install 20.04 specific programs
  apt:
    name: "{{ install.common.focal }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"
