---

- name: Add Neovim PPA
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'
    state: present
  become: yes

- name: Install Neovim
  apt:
    name: neovim
    update_cache: yes
    state: latest
  become: yes
