---

- name: Add Neovim PPA
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'
    state: present
  become: yes
  when:
    - ansible_distribution == 'Ubuntu'
    # Arm64 not yet in the PPA
    - ansible_architecture != 'aarch64'
    # The repo does not support 20.04, but it has nvim in the default repo
    - ansible_distribution_version != "20.04"

- name: Install Neovim
  apt:
    name: neovim
    update_cache: yes
    state: latest
  become: yes
