---
- import_tasks: hostname.yaml
- import_tasks: timezone.yaml
- import_tasks: configure-apt.yaml
- import_tasks: packages.yaml
- import_tasks: sshd-harden.yaml
- import_tasks: dotfiles.yaml
- import_tasks: modify-sudo.yaml
