---
- name: Set hostname
  ansible.builtin.import_tasks: hostname.yaml

- name: Set timezone
  ansible.builtin.import_tasks: timezone.yaml

- name: Configure apt
  ansible.builtin.import_tasks: configure-apt.yaml

- name: Install packages
  ansible.builtin.import_tasks: packages.yaml

- name: Harden SSH
  ansible.builtin.import_tasks: sshd-harden.yaml

- name: Generate outbound SSH keys
  ansible.builtin.import_tasks: ssh-keys.yaml

- name: Authorize incoming SSH keys
  ansible.builtin.import_tasks: ssh-authorize.yaml

- name: Deploy dotfiles and repos
  ansible.builtin.import_tasks: dotfiles.yaml

- name: Configure sudo
  ansible.builtin.import_tasks: modify-sudo.yaml
