---

# Update all installed packages

- name: Apt install "aptitude"
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Update all packages
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 3600
  become: true
