---
name: Lint
on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install ansible-lint yamllint

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml

      # Must match vault_password_file in ansible.cfg and the actual vault
      # password.
      - name: Create vault password file
        run: echo "$VAULT_PASSWORD" > .vault_pass.txt
        env:
          VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}

      - name: YAML lint
        run: yamllint -s .

      - name: Ansible syntax check
        run: ansible-playbook site.yaml --syntax-check

      - name: Ansible lint
        run: ansible-lint

      - name: Remove vault password file
        if: always()
        run: rm -f .vault_pass.txt
