---
name: Lint
on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install ansible-lint yamllint

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: YAML lint
        run: yamllint -s .

      - name: Ansible syntax check
        run: ansible-playbook site.yaml --syntax-check

      - name: Ansible lint
        run: ansible-lint
